name: AI DE&S Daily Scraper

on:
  schedule:
    - cron: '0 3 * * *'
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Scraper Pipeline
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          TARGET_MODE: ${{ vars.TARGET_MODE }}
          URLS_FILE_PATH: "config/sites_vagas.txt"
        run: python app/main.py

      - name: Commit and Push Results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add data/
          git commit -m "Auto: Dados extraídos em $(date +'%Y-%m-%d')" || echo "Sem mudanças para commitar"
          git push